### ISSUE TITLE
waitlist: finalize page design

### ISSUE THREAD

**Issue by srivatsav-kannan** [ProjectAviquo/aviquo#43]
Final touches, Replace ALL hardcoded px values with something else for responsiveness, however the layout and style MUST NOT change

**Comment by Leo-MathGuy** [comment]
Finishing touches? I think it needs like a rework of the html structure because the css responsiveness is bad and the scrolling is glitchy

**Comment by srivatsav-kannan** [comment]
Scrolling is fine. But we do have to replace all hard-coded px values with something else

**Comment by srivatsav-kannan** [comment]
Text font is wrong. Margins janky. Discord background should not have gradient

**Comment by srivatsav-kannan** [comment]
Leo will be redesigning the entire page, he will hopefully be done soon

**Comment by Leo-MathGuy** [comment]
Soon
