### ISSUE TITLE
waitlist: finish re-doing frontend

### ISSUE THREAD

**Issue by Leo-MathGuy** [ProjectAviquo/aviquo#67]
Idk everyone is talking about it and I'm doing it rn so like

**Comment by BRama10** [comment]
@Leo-MathGuy Didn't we discuss not using Tailwind since it's not suitable for our puposes?

**Comment by Leo-MathGuy** [comment]
It's a third party library so what it works it's 2.0 not 0.0.5.1 and like I can implement it if I want to and like tailwind is super useful I remade the header in 30 mins instead of 2 hours
